version: '2'

services:
  app:
    build:
      context: gitbucket
    volumes:
      - /opt/docker/gitbucket/volumes/gitbucket/opt/gitbucket:/opt/gitbucket
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8000:8080"
